### ISSUE TITLE
failed with 'FailedConnectionException "

### ISSUE THREAD

**Issue by 11111000000** [NoRedInk/take-home#21]
failed with 'FailedConnectionException "github.com" 443' when sending request to
    http://github.com/evancz/virtual-dom/zipball/2.1.0/
/home/az/justforfun/ELM/take-home/instance/server/main.js:1
(function (exports, require, module, __filename, __dirname) { Elm.worker(Elm.Main);
                                                              ^

ReferenceError: Elm is not defined
    at Object.<anonymous> (/home/az/justforfun/ELM/take-home/instance/server/main.js:1:63)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3

**Comment by 11111000000** [comment]
third retry success completely
